Fix compilation error: Use Color.value instead of Color.toARGB32
Changed border.top.color.toARGB32 to border.top.color.value since toARGB32 doesn't exist.
The Color class uses .value property to get the int representation of the color.